name: release
on:
  # pull_request:
  #   branches:
  #     - main
  push:
    tags:
      - "v*" # Run if someone pushes a semantic versioned tag to the GitHub repo

env:
  APPEND_BUILD_NUMBER: false

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0

      - name: read version from tag
        id: version_read
        run: echo "tag_version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        shell: bash

      # https://github.com/marketplace/actions/semver-utils
      - uses: madhead/semver-utils@latest
        id: version
        with:
          # Fail the task if it can't parse the version
          lenient: false
          # The ref_name will be the version tag
          version: ${{ github.ref_name }}

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: setup jdk 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build
        env:
          MOD_VERSION: ${{ steps.version.outputs.release }}

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: build/libs/

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: v${{ steps.version.outputs.release }} for ${{ steps.version.outputs.build }}
          version: ${{ steps.version.outputs.release }}+${{ steps.version.outputs.build }}
          version-type: release

          github-generate-changelog: true
          github-draft: false
          github-prerelease: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files-primary: build/libs/!(*-@(dev|sources|javadoc)).jar
          files-secondary: build/libs/*-@(dev|sources|javadoc).jar

          #modrinth-id: Read from fabric.mod.json custom.modmanager.modrinth
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          #curseforge-id: Read from fabric.mod.json custom.modmanager.curseforge
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
