name: release
on:
  push:
    tags:
      - 'v*' # Run if someone pushes a semantic versioned tag to the GitHub repo

env:
  APPEND_BUILD_NUMBER: false

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: read version from tag
        id: version_read
        run: echo "tag_version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        shell: bash

      # https://github.com/marketplace/actions/semver-utils
      - uses: madhead/semver-utils@latest
        id: version
        with:
          # Fail the task if it can't parse the version
          lenient: false
          version: ${{ env.tag_version }}

      #TODO: Instead of parsing the git tag, we should just read the property from gradle.properties
      - name: log parsed semver
        id: version_log
        shell: bash
        run: |
          echo "release = ${{ steps.version.outputs.release }}"   # Mod Version
          echo "build = ${{ steps.version.outputs.build }}"       # Minecraft Version

      - name: checkout repository
        uses: actions/checkout@v2

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: build/libs/

      - name: get changelog entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: error
          version: ${{ steps.version.outputs.release }}
          path: ./CHANGELOG.md

      - uses: Kir-Antipov/mc-publish@v3.2
        if: ${{ github.event.inputs.test-run != 'y' }}
        with:
          name: v${{ steps.version.outputs.release }} for ${{ steps.version.outputs.build }}
          version: ${{ steps.version.outputs.release }}+${{ steps.version.outputs.build }}
          version-type: release
          changelog-file: CHANGELOG.md
          changelog: ${{ steps.changelog_reader.outputs.changes }}

          loaders: |
            fabric
          game-versions: |
            1.19.3
          dependencies: |
            fabric-api | depends | *
            cloth-config | depends | *
            modmenu | suggests | *
          java: |
            17

          files-primary: build/libs/!(*-@(dev|sources|javadoc)).jar

          #modrinth-id: Read from fabric.mod.json custom.modmanager.modrinth
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          #curseforge-id: Read from fabric.mod.json custom.modmanager.curseforge
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-generate-changelog: false
          github-draft: false
          github-prerelease: false
          github-discussion: Announcements
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-files-secondary: build/libs/*-@(dev|sources|javadoc).jar

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
